### PR TITLE
Huggingface/hf hub

### PR DESCRIPTION
**Pull request by nickprock**
** Integration with HuggingFace Hub**
Issue #66 

Developed the support for huggingface hub:
* updated the hooks in [models.py](https://github.com/pieroit/cheshire-cat/blob/main/web/cat/plugins/quickstart_cat_plugin/models.py#L30)
* Developed the embedder for huggingface hub using langchain
* tested with some models: 
  * [openai-gpt](https://huggingface.co/openai-gpt), 
  * [llama](decapoda-research/llama-13b-hf), 
  * [alpaca-lora](https://huggingface.co/declare-lab/flan-alpaca-xxl)
* updated readme

### CODE REVIEW

**Comment by nickprock** [comment]
At the moment the condition in the hook for the language model is:

```python
elif "HF_TOKEN" in os.environ:
        llm = llms.LLMHuggingFaceHubConfig.get_llm_from_config(
                {
                    "huggingfacehub_api_token": os.environ["HF_TOKEN"],
                    "repo_id" : os.environ["HF_CHECKPOINT"]
                }
        )
```

but we need a second control, do you want it like this

```python
elif "HF_TOKEN" in os.environ and "HF_CHECKPOINT" in os.environ:
        llm = llms.LLMHuggingFaceHubConfig.get_llm_from_config(
                {
                    "huggingfacehub_api_token": os.environ["HF_TOKEN"],
                    "repo_id" : os.environ["HF_CHECKPOINT"]
                }
        )
```

or

```python
elif "HF_TOKEN" in os.environ:
        if "HF_CHECKPOINT" in os.environ:
             llm = llms.LLMHuggingFaceHubConfig.get_llm_from_config(
                   {
                       "huggingfacehub_api_token": os.environ["HF_TOKEN"],
                       "repo_id" : os.environ["HF_CHECKPOINT"]
                   }
             )
       else:
          llm = llms.LLMHuggingFaceHubConfig.get_llm_from_config(
                   {
                       "huggingfacehub_api_token": os.environ["HF_TOKEN"],
                       "repo_id" : a_default_checkpoint
                   }
             )
```

?

**Comment by pieroit** [comment]
Default checkpoint looks a good idea to me!
Thanks, should I wait to merge?

**Comment by nickprock** [comment]
now there should be the fix working, you can merge

**Comment by pieroit** [comment]
Thanks!!!

**Pull request merged**
